version: '2'

services:
  ckan-db:
    image: postgres:9.6.0
    container_name: ckan-hobbit-db
    environment:
      - POSTGRES_PASSWORD=ckan
      - POSTGRES_USER=ckan
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=ckan
    volumes:
      - ./data/ckan-hobbit-db:/var/lib/postgresql/data
    restart: always

  ckan-solr:
    image: earthquakesan/ckan-solr:2.8.0
    container_name: ckan-hobbit-solr
    restart: always

  ckan-redis:
    image: redis:4.0.11
    restart: always
  
  #ckan-datapusher:
  #  image: earthquakesan/ckan-datapusher:latest
  #  restart: always

  ckan:
    image: mwauer/ckan:2.8.1-opal
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@ckan-db:5432/ckan
      - CKAN_SOLR_URL=http://ckan-solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://ckan-redis:6379/0
      - CKAN_DATAPUSHER_URL=http://ckan-datapusher:8800/
      - CKAN_SITE_URL=http://localhost:5000
      - CKAN_SITE_TITLE=OPAL CKAN
      - CKAN_SITE_DESCRIPTION=CKAN-Portal des Forschungsprojekts OPAL
      - CKAN_RECAPTCHA_PUBLICKEY=${CKAN_RECAPTCHA_PUBLICKEY}
      - CKAN_RECAPTCHA_PRIVATEKEY=${CKAN_RECAPTCHA_PRIVATEKEY}
      - REDIS_HOSTNAME=ckan-redis
      #- DEBUG=true
    volumes:
      - ./ckan-storage:/var/lib/ckan
#      - ./ckan-config:/etc/ckan
#      - ./ckan-home:/usr/lib/ckan
    restart: always
    ports:
      - 5000:5000
  fileStorage:
    image: busybox
    volumes:
      - /files
  fileServer:
    image: mnafshin/simple_file_server
    volumes_from:
      - fileStorage:ro
    restart: always
    ports:
      - "8000:8000"
  fuseki-data:
    image: busybox
    volumes:
      - /fuseki
  civetTripleStore:
    image: stain/jena-fuseki
    volumes_from:
      - fuseki-data:rw
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx15g 
  conversionTool:
    image: mnafshin/conversion-tool
    environment:
      - CRAWLER_TRIPLESTORE_URL=${CRAWLER_TRIPLESTORE_URL}
      - CRAWLER_TRIPLESTORE_USERNAME=${CRAWLER_TRIPLESTORE_USERNAME}
      - CRAWLER_TRIPLESTORE_PASSWORD=${CRAWLER_TRIPLESTORE_PASSWORD}
      - CIVET_TRIPLESTORE_URL=civetTripleStore
    ports:
      - "8080:8080"
  tripleStoreDumper:
    image: mnafshin/triple-store-dumper
    volumes_from:
      - fileStorage:rw
    environment:
      - CIVET_TRIPLESTORE_URL=civetTripleStore
      - TRIPLESTORE_USERNAME=admin
      - TRIPLESTORE_PASSWORD=admin
      - INTERNAL_FILESERVER_ADDRESS=fileServer
      - OUTPUT_FOLDER_PATH=/files
    ports:
      - "8081:8081"     
